const fs = require('fs');

var regionIds = {
  "Contiguous 48 U.S. States & Canada": 0,
  "Alaska": 1,
  "Hawaii": 2,
  "The Caribbean": 3,
  "Mexico": 4,
  "Central America": 5,
  "South America 1": 6,
  "South America 2": 7,
  "Europe": 8,
  "Middle East": 9,
  "Indian Subcontinent": 10,
  "Africa": 11,
  "Asia 1": 12,
  "Asia 2": 13,
  "South Pacific": 14,
};

var regions = {
  // "Afghanistan": "Central Asia", not listed
  "Alaska": "Contiguous 48 U.S. States & Canada",
  "Albania": "Europe",
  "Algeria": "Africa",
  "American Samoa": "South Pacific",
  "Anguilla": "The Caribbean",
  "Angola": "Africa",
  "Antigua and Barbuda": "The Caribbean",
  "Argentina": "South America 2",
  "Armenia": "Europe",
  "Aruba": "The Caribbean",
  "Austria": "Europe",
  "Azerbaijan": "Europe",
  "Bahamas": "The Caribbean",
  "Bahrain": "Middle East",
  "Bangladesh": "Indian Subcontinent",
  "Barbados": "The Caribbean",
  "Belarus": "Europe",
  "Belgium": "Europe",
  "Belize": "Central America",
  // "Benin": "Central & Southern Africa", not lsited
  "Bermuda": "The Caribbean",
  // "Bhutan": "South Asia", not listed
  "Bolivia": "South America 1",
  // "Bosnia & Herzegovina": "Europe", not listed
  // "Botswana": "Central & Southern Africa", not listed
  "Brazil": "South America 2", // divided in manaus...
  "British Virgin Islands": "The Caribbean",
  "Brunei": "Asia 2",
  "Bulgaria": "Europe",
  // "Burkina Faso": "Central & Southern Africa", not listed
  // "Burundi": "Central & Southern Africa", not listed
  "Cambodia": "Asia 2",
  // "Cameroon": "Central & Southern Africa",
  "Canada": "Contiguous 48 U.S. States & Canada",
  "Canary Islands": "Europe", // Part of Spain
  // "Cape Verde": "Central & Southern Africa",
  "Cayman Islands": "The Caribbean",
  // "Central African Republic": "Central & Southern Africa",
  // "Chad": "Central & Southern Africa",
  "Chile": "South America 2",
  "China": "Asia 2",
  "Colombia": "South America 1",
  // "Comoros": "Central & Southern Africa",
  "Cook Islands": "South Pacific",
  "Costa Rica": "Central America",
  // "Cote d'Ivoire": "Central & Southern Africa",
  "Croatia": "Europe",
  "Cuba": "The Caribbean",
  "Cyprus": "Europe",
  "Czech Republic": "Europe",
  // "Congo (Brazzaville)": "Central & Southern Africa",
  // "Congo (Kinshasa)": "Central & Southern Africa",
  "Denmark": "Europe",
  "Djibouti": "Africa",
  "Dominica": "The Caribbean",
  "Dominican Republic": "The Caribbean",
  "Ecuador": "South America 1",
  "Egypt": "Middle East",
  "El Salvador": "Central America",
  "Equatorial Guinea": "Africa",
  // "Eritrea": "Africa",
  "Estonia": "Europe",
  "Ethiopia": "Central & Southern Africa",
  "Fiji": "South Pacific",
  "Finland": "Europe",
  "France": "Europe",
  // "French Guiana": "South America 1",
  "French Polynesia": "South Pacific",
  // "Gabon": "Central & Southern Africa",
  // "Gambia": "Central & Southern Africa",
  "Georgia": "Europe",
  "Germany": "Europe",
  "Ghana": "Africa",
  "Greece": "Europe",
  "Greenland": "Europe",
  "Grenada": "The Caribbean",
  "Guadeloupe": "The Caribbean",
  "Guam": "South Pacific",
  "Guatemala": "Central America",
  // "Guinea": "Central & Southern Africa",
  // "Guinea-Bissau": "Central & Southern Africa",
  // "Guyana": "South America 1", NOT LISTED
  "Haiti": "The Caribbean",
  "Hawaii": "Hawaii", // Part of U.S.
  "Honduras": "Central America",
  "Hong Kong": "Asia 2",
  "Hungary": "Europe",
  "Iceland": "Europe",
  "India": "Indian Subcontinent",
  "Indonesia": "Asia 2",
  "Iran": "Middle East",
  "Iraq": "Middle East",
  "Ireland": "Europe",
  "Israel": "Middle East",
  "Italy": "Europe",
  "Jamaica": "The Caribbean",
  "Japan": "Asia 1",
  "Jordan": "Middle East",
  "Kazakhstan": "Indian Subcontinent",
  "Kenya": "Africa",
  "Kuwait": "Middle East",
  // "Kyrgyzstan": "Central Asia",
  // "Laos": "South Asia",
  "Latvia": "Europe",
  "Lebanon": "Middle East",
  // "Lesotho": "Central & Southern Africa",
  // "Liberia": "Central & Southern Africa",
  // "Libya": "Northern Africa",
  "Lithuania": "Europe",
  "Luxembourg": "Europe",
  // "Macau": "South Asia",
  "Macedonia": "Europe",
  // "Madagascar": "Central & Southern Africa",
  // "Malawi": "Central & Southern Africa",
  "Malaysia": "Asia 2",
  "Maldives": "Indian Subcontinent",
  // "Mali": "Central & Southern Africa",
  // "Malta": "Europe",
  // "Marshall Islands": "Oceania",
  "Martinique": "The Caribbean",
  // "Mauritania": "Central & Southern Africa",
  "Mauritius": "Africa",
  "Mexico": "Mexico",
  // "Micronesia": "Oceania",
  "Moldova": "Europe",
  // "Mongolia": "North Asia",
  "Montenegro": "Europe",
  "Morocco": "Africa",
  "Mozambique": "Africa",
  "Myanmar": "Asia 2",
  "Namibia": "Africa",
  "Nepal": "Indian Subcontinent",
  "Netherlands": "Europe",
  "Netherlands Antilles": "The Caribbean",
  "New Caledonia": "South Pacific",
  "Nicaragua": "Central America",
  // "Niger": "Central & Southern Africa",
  "Nigeria": "Africa",
  // "Northern Mariana Islands": "Oceania",
  "Norway": "Europe",
  "Oman": "Middle East",
  "Pakistan": "Indian Subcontinent",
  "Palau": "South Pacific",
  "Panama": "Central America",
  "Papua New Guinea": "South Pacific",
  "Paraguay": "South America 2",
  "Peru": "South America 1",
  "Philippines": "Asia 2",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Puerto Rico": "The Caribbean",
  "Qatar": "Middle East",
  // "Reunion": "Central & Southern Africa",
  "Romania": "Europe",
  "Russia": "Europe",
  "Rwanda": "Africa",
  "Samoa": "South Pacific",
  // "Sao Tome and Principe": "Central & Southern Africa",
  "Saudi Arabia": "Middle East",
  "Senegal": "Africa",
  "Serbia": "Europe",
  "Seychelles": "Africa",
  "Sierra Leone": "Africa",
  "Singapore": "Asia 2",
  // "Slovakia": "Europe",
  "Slovenia": "Europe",
  // "Somalia": "Central & Southern Africa",
  "South Africa": "Africa",
  "South Korea": "Asia 1",
  // "South Sudan": "Central & Southern Africa",
  "Spain": "Europe",
  "Sri Lanka": "Indian Subcontinent",
  "Saint Kitts and Nevis": "The Caribbean",
  "Santa Lucia": "The Caribbean",
  "Sudan": "Africa",
  "Suriname": "South America 1",
  // "Swaziland": "Central & Southern Africa",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  // "Syria": "Middle East",
  "Taiwan": "Asia 2",
  // "Tajikistan": "Central Asia",
  "Tanzania": "Africa 2",
  "Thailand": "Asia 2",
  // "Togo": "Central & Southern Africa",
  "Tonga": "South Pacific",
  "Trinidad and Tobago": "The Caribbean",
  "Tunisia": "Africa",
  "Turkey": "Europe",
  "Turkmenistan": "Indian Subcontinent",
  // "Turks and Caicos Islands": "The Caribbean",
  "Uganda": "Africa",
  "Ukraine": "Europe",
  "United Arab Emirates": "Middle East",
  "United Kingdom": "Europe",
  "United States": "Contiguous 48 U.S. States & Canada",
  "Uruguay": "South America 2",
  "Uzbekistan": "Indian Subcontinent",
  "Vanuatu": "South Pacific",
  "Venezuela": "South America 2",
  "Vietnam": "Asia 2",
  "Virgin Islands": "The Caribbean",
  // "Yemen": "Middle East",
  "Zambia": "Africa",
  "Zimbabwe": "Africa",
};

var alaskaAirports = [
  "MRI", "ANC", "ANI", "BRW", "BET",
  "CDV", "SCC", "DLG", "FAI", "GAL",
  "HOM", "JNU", "ENA", "KTN", "AKN",
  "ADQ", "OTZ", "OME", "PSG", "SIT",
  "KSM", "UNK", "DUT", "VDZ", "WRG",
  "YAK", "AUK", "AKP", "BKC", "CYF",
  "VAK", "CDB", "CXF", "CGA", "EEK",
  "EMK", "FYU", "GAM", "GST", "HNS",
  "HNH", "HPB", "HSL", "ILI", "BTI",
  "KLG", "KUK", "IAN", "KPN", "KVL",
  "KVL", "KLW", "KKH", "KOT", "KWT",
  "KWK", "KLN", "KMO", "MLL", "MCG",
  "MTM", "MOU", "WWT", "WTK", "ORV",
  "NUP", "OLH", "PQS", "PHO", "KWN",
  "RSH", "SNP", "SDP", "SVA", "SCM",
  "WLK", "SOV", "SHH", "SGY", "TAL",
  "KTB", "OOK", "TLT", "WTL", "AIN"
];
